# Generated by Django 3.2.13 on 2022-09-14 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0005_auto_20220914_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char_category_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Max_No_of_char_allowed', models.IntegerField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Character Limit',
                'verbose_name_plural': 'Character Limits',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 18, 13, 43, 617624), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 18, 13, 43, 617624), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 18, 13, 43, 618624), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 18, 13, 43, 617624), null=True),
        ),
    ]
