# Generated by Django 3.2.13 on 2022-09-15 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0007_auto_20220914_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 13, 17, 1, 385525), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 13, 17, 1, 385525), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 13, 17, 1, 385525), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 13, 17, 1, 385525), null=True),
        ),
    ]
