# Generated by Django 3.2.13 on 2022-09-15 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0012_auto_20220915_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='_Name',
            new_name='lng_Name',
        ),
        migrations.RenameField(
            model_name='languages',
            old_name='_slug',
            new_name='lng_slug',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 18, 38, 36, 983738), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 18, 38, 36, 983738), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 18, 38, 36, 984738), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 18, 38, 36, 983738), null=True),
        ),
    ]
