# Generated by Django 3.2.13 on 2022-09-15 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0013_auto_20220915_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 19, 7, 39, 222388), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 19, 7, 39, 222388), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 19, 7, 39, 223388), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 19, 7, 39, 223388), null=True),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='language_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.languages'),
        ),
    ]
