# Generated by Django 4.1.1 on 2022-10-01 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0006_sellerlevels_user_avg_respons_user_last_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 13, 20, 39, 313568), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 13, 20, 39, 313568), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 13, 20, 39, 314568), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 13, 20, 39, 314568), null=True),
        ),
        migrations.AlterField(
            model_name='sellerlevels',
            name='level_name',
            field=models.CharField(blank=True, choices=[('level1', 'Level One'), ('level2', 'Level Two')], default='Basic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_level',
            field=models.CharField(blank=True, choices=[('level1', 'Level One'), ('level2', 'Level Two'), ('top_rated', 'Top Rated Seller')], default='level1', max_length=200, null=True),
        ),
    ]
