# Generated by Django 4.1.1 on 2022-10-01 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0007_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('gig_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.categories')),
                ('gig_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.subsubcategories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gig Details',
                'verbose_name_plural': 'User Gig Details',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 47, 29, 731369), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 47, 29, 731369), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 47, 29, 732369), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 47, 29, 732369), null=True),
        ),
        migrations.CreateModel(
            name='UserGigsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_tag_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gig Tags',
                'verbose_name_plural': 'User Gig Tags',
            },
        ),
        migrations.CreateModel(
            name='Category_package_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.subsubcategories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Package Details',
                'verbose_name_plural': 'Category Package Details',
            },
        ),
    ]
