# Generated by Django 4.1.1 on 2022-10-01 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0008_usergigs_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_package_details',
            options={'verbose_name': 'Category Package', 'verbose_name_plural': 'Category Packages'},
        ),
        migrations.AddField(
            model_name='category_package_details',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category_package_details',
            name='display_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('boolean', 'Boolean'), ('textbox', 'TextArea')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 52, 16, 558306), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 52, 16, 558306), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 52, 16, 559307), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 15, 52, 16, 559307), null=True),
        ),
        migrations.CreateModel(
            name='Category_package_Extra_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('display_type', models.CharField(blank=True, choices=[('number', 'Number'), ('boolean', 'Boolean'), ('textbox', 'TextArea')], max_length=200, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.subsubcategories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Extra Services',
                'verbose_name_plural': 'Category Extra Services',
            },
        ),
    ]
