# Generated by Django 4.1.1 on 2022-10-01 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0009_alter_category_package_details_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_package_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='category_package_extra_service',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 49, 20, 195136), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 49, 20, 195136), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 49, 20, 195136), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 49, 20, 195136), null=True),
        ),
    ]
