# Generated by Django 4.1.1 on 2022-10-01 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0010_remove_category_package_details_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_package_details',
            name='display_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('boolean', 'Boolean')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 58, 13, 727939), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 58, 13, 727939), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 58, 13, 728940), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 18, 58, 13, 728940), null=True),
        ),
    ]
