# Generated by Django 4.1.1 on 2022-10-01 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0011_alter_category_package_details_display_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(blank=True, choices=[('delivery_time', 'Delivery Time'), ('extra_days', 'Extra Days'), ('extra_time', 'Extra Time'), ('no_revisions', 'No. of Revisions')], max_length=200, null=True)),
                ('parameter_value', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Add On Gig Params',
                'verbose_name_plural': 'Add On Gig Params',
            },
        ),
        migrations.AlterField(
            model_name='category_package_extra_service',
            name='display_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('boolean', 'Boolean'), ('textbox', 'TextArea'), ('extra_days', 'Extra Days'), ('extra_time', 'Extra Time')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 27, 11, 99869), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 27, 11, 99869), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 27, 11, 99869), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 27, 11, 99869), null=True),
        ),
    ]
