# Generated by Django 4.1.1 on 2022-10-01 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0012_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_package_extra_service',
            name='display_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('boolean', 'Boolean'), ('textbox', 'TextArea'), ('extra_days', 'Extra Days'), ('extra_time', 'Extra Time'), ('non', 'None')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 28, 25, 452651), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 28, 25, 452651), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 28, 25, 452651), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 19, 28, 25, 452651), null=True),
        ),
    ]
