# Generated by Django 4.1.1 on 2022-10-02 12:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0014_characterlimit_hint_text_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergigs',
            options={'verbose_name': 'Gig Details', 'verbose_name_plural': 'Gig Details'},
        ),
        migrations.AlterModelOptions(
            name='usergigstags',
            options={'verbose_name': 'Gig Tags', 'verbose_name_plural': 'Gig Tags'},
        ),
        migrations.AddField(
            model_name='usergigs',
            name='gig_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usergigs',
            name='gig_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('modification', 'Modification'), ('draft', 'Draft'), ('denied', 'Denied'), ('paused', 'Paused')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 12, 3, 37, 484862), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 12, 3, 37, 484862), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 12, 3, 37, 485863), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 12, 3, 37, 485863), null=True),
        ),
        migrations.AlterField(
            model_name='usergigs',
            name='gig_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.categories'),
        ),
        migrations.AlterField(
            model_name='usergigs',
            name='gig_sub_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.subsubcategories'),
        ),
        migrations.CreateModel(
            name='UserGigPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], max_length=200, null=True)),
                ('package_title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('package_description', models.TextField(blank=True, default='', null=True)),
                ('package_data', models.TextField(blank=True, default='', null=True)),
                ('package_price', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('package_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_delivery', to='kworkapp.parameter')),
                ('package_gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('package_revisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_revisions', to='kworkapp.parameter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Packages',
                'verbose_name_plural': 'Gig Packages',
            },
        ),
        migrations.CreateModel(
            name='UserGigPackage_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_data', models.TextField(blank=True, default='', null=True)),
                ('package_gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Package Extra',
                'verbose_name_plural': 'Gig Package Extra',
            },
        ),
        migrations.CreateModel(
            name='Usergig_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_req_question', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('gig_req_ans_type', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('package_gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Requirement',
                'verbose_name_plural': 'Gig Requirements',
            },
        ),
        migrations.CreateModel(
            name='Usergig_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_image', models.ImageField(blank=True, upload_to='')),
                ('package_gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Image',
                'verbose_name_plural': 'Gig Images',
            },
        ),
        migrations.CreateModel(
            name='Usergig_faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_faq_question', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('gig_faq_answer', models.TextField(blank=True, default='', null=True)),
                ('package_gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gig Faq',
                'verbose_name_plural': 'Gig Faqs',
            },
        ),
        migrations.CreateModel(
            name='UserExtra_gigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_gig_title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('extra_gig_description', models.TextField(blank=True, default='', null=True)),
                ('extra_gig_price', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('extra_gig_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.parameter')),
                ('package_gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extra Gig',
                'verbose_name_plural': 'Extra Gigs',
            },
        ),
    ]
