# Generated by Django 4.1.1 on 2022-10-02 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0017_alter_category_package_extra_service_display_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_package_extra_service',
            name='display_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('extra_time', 'Extra Time'), ('none', 'None')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 20, 9, 36, 891454), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 20, 9, 36, 892455), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 20, 9, 36, 893456), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 2, 20, 9, 36, 892455), null=True),
        ),
    ]
