# Generated by Django 4.1.1 on 2022-10-05 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0021_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 5, 13, 37, 45, 137541), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 5, 13, 37, 45, 137541), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 5, 13, 37, 45, 138541), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 5, 13, 37, 45, 137541), null=True),
        ),
        migrations.AlterField(
            model_name='usergigs',
            name='gig_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('modification', 'Modification'), ('draft', 'Draft'), ('denied', 'Denied'), ('paused', 'Paused')], default='draft', max_length=200, null=True),
        ),
    ]
