# Generated by Django 4.1.1 on 2022-10-09 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0023_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergigs',
            name='gig_impressions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 19, 42, 8, 522914), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 19, 42, 8, 522914), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 19, 42, 8, 522914), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 19, 42, 8, 522914), null=True),
        ),
    ]
