# Generated by Django 4.1.1 on 2022-10-09 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0024_usergigs_gig_impressions_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 1, 49, 663455), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 1, 49, 663455), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 1, 49, 663455), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 1, 49, 663455), null=True),
        ),
        migrations.CreateModel(
            name='UserAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('available_to', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('available_mssg', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('available_for_new', models.BooleanField(default=False)),
                ('available_types', models.CharField(blank=True, choices=[('vacation', "I'm going on vacation"), ('overbooked', "I'm overbooked"), ('other', 'Other')], max_length=200, null=True)),
                ('gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Available',
                'verbose_name_plural': 'User Available',
            },
        ),
    ]
