# Generated by Django 4.1.1 on 2022-10-09 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0025_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_words', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('search_types', models.CharField(blank=True, choices=[('user', 'user'), ('keyword', 'keyword')], max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'User Search Term',
                'verbose_name_plural': 'User Search Terms',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 13, 33, 963022), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 13, 33, 963022), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 13, 33, 964022), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 20, 13, 33, 963022), null=True),
        ),
    ]
