# Generated by Django 4.1.1 on 2022-10-10 03:40

import datetime
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0027_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 3, 40, 41, 636826), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 3, 40, 41, 636826), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 3, 40, 41, 637827), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 3, 40, 41, 637827), null=True),
        ),
        migrations.AlterField(
            model_name='user_orders',
            name='order_no',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456', length=6, max_length=6, prefix='', primary_key=True, serialize=False),
        ),
    ]
