# Generated by Django 4.1.1 on 2022-10-10 05:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0029_remove_usergigs_gig_impressions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 5, 54, 58, 750710), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 5, 54, 58, 750710), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 5, 54, 58, 750710), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 5, 54, 58, 750710), null=True),
        ),
        migrations.AlterField(
            model_name='usergigsimpressions',
            name='impress_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
