# Generated by Django 4.1.1 on 2022-10-11 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0035_buyer_reviews_rating_val_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer_reviews',
            old_name='s_review_from',
            new_name='b_review_from',
        ),
        migrations.RenameField(
            model_name='buyer_reviews',
            old_name='s_review_to',
            new_name='b_review_to',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 0, 32, 0, 321427), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 0, 32, 0, 321427), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 0, 32, 0, 322428), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 0, 32, 0, 322428), null=True),
        ),
    ]
