# Generated by Django 4.1.1 on 2022-10-23 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0039_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_post_request',
            name='send_to',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_send_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer_post_request',
            name='service_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('all', 'All')], default='Basic', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 16, 52, 47, 213090), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 16, 52, 47, 213090), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 16, 52, 47, 214091), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 23, 16, 52, 47, 213090), null=True),
        ),
    ]
