# Generated by Django 4.1.1 on 2022-10-16 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0050_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchterms',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 11, 0, 16, 344367), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 11, 0, 16, 344367), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 11, 0, 16, 345368), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 11, 0, 16, 345368), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avg_delivery_time',
            field=models.CharField(blank=True, default='Within 24 Hours', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avg_respons',
            field=models.CharField(blank=True, default='1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ordersin_progress',
            field=models.CharField(blank=True, default='0', max_length=500, null=True),
        ),
    ]
