# Generated by Django 4.1.1 on 2022-10-16 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0052_buyer_post_request_service_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 18, 46, 7, 616366), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 18, 46, 7, 616366), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 18, 46, 7, 616366), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 18, 46, 7, 616366), null=True),
        ),
        migrations.CreateModel(
            name='Request_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_desc', models.TextField()),
                ('offer_budget', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('offer_time', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('no_revisions', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('ask_requirements', models.BooleanField(default=False)),
                ('extra_parameters', models.TextField()),
                ('buyer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.buyer_post_request')),
                ('gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Offer',
                'verbose_name_plural': 'Request Offers',
            },
        ),
    ]
