# Generated by Django 4.1.1 on 2022-10-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0056_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_offers',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('custom', 'Custom'), ('request', 'Request')], default='all', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 7, 0, 10, 10057), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 7, 0, 10, 10057), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 7, 0, 10, 10057), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 7, 0, 10, 10057), null=True),
        ),
    ]
