# Generated by Django 4.0.8 on 2022-10-20 22:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0062_payment_parameters_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_days', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Parameter',
                'verbose_name_plural': 'Withdrawal Parameters',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 3, 57, 23397), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 3, 57, 23397), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 3, 57, 39022), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 3, 57, 23397), null=True),
        ),
        migrations.CreateModel(
            name='User_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('paypal', 'Paypal'), ('flutterwave', 'Flutterwave')], default='', max_length=300, null=True)),
                ('transaction_id', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('payment_status', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('paypal_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('card_no', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.request_offers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
