# Generated by Django 4.0.8 on 2022-10-20 22:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0063_withdrawal_parameters_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 8, 38, 13775), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 8, 38, 13775), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 8, 38, 14775), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 22, 8, 38, 13775), null=True),
        ),
        migrations.CreateModel(
            name='Buyer_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_ques', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('default_req', models.BooleanField(default=False)),
                ('requirement_ans', models.TextField(blank=True, default='', null=True)),
                ('req_documents', models.TextField(blank=True, default='', null=True)),
                ('gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Requirement',
                'verbose_name_plural': 'Buyer Requirements',
            },
        ),
    ]
