# Generated by Django 4.0.8 on 2022-10-21 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0069_user_transactions_flutter_app_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 17, 37, 24, 114402), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 17, 37, 24, 114402), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 17, 37, 24, 114402), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 17, 37, 24, 114402), null=True),
        ),
        migrations.AlterField(
            model_name='user_transactions',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_transactions',
            name='transaction_ref',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
