# Generated by Django 4.0.8 on 2022-10-27 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0076_user_avail_bal_user_cancelled_earning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Order_Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(blank=True, choices=[('cancel', 'Cancel Order'), ('extention', 'Extension Days')], default='', max_length=300, null=True)),
                ('resolution_text', models.CharField(blank=True, max_length=500, null=True)),
                ('resolution_message', models.CharField(blank=True, max_length=200, null=True)),
                ('resolution_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('resolution_personal_msg', models.CharField(blank=True, max_length=1000, null=True)),
                ('resolution_days', models.CharField(blank=True, max_length=200, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('resolution_status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='', max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Order Resolution Center',
                'verbose_name_plural': 'Order Resolution Center',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 13, 11, 45, 780203), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 13, 11, 45, 780203), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 13, 11, 45, 782204), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 13, 11, 45, 781204), null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_name',
            field=models.CharField(blank=True, choices=[('delivery_time', 'Delivery Time'), ('extra_days', 'Extra Days'), ('extra_time', 'Extra Time'), ('no_revisions', 'No. of Revisions'), ('res_days', 'Resolution Days')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='User_Order_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('activity_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
            ],
            options={
                'verbose_name': 'Order Activity',
                'verbose_name_plural': 'Order Activities',
            },
        ),
    ]
