# Generated by Django 4.0.8 on 2022-10-28 12:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0081_user_current_earning_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_convo_starter', to=settings.AUTH_USER_MODEL)),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_convo_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Conversation',
                'verbose_name_plural': 'Order Conversations',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('chat', 'Chat Message'), ('activity', 'Activity Message')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 12, 59, 14, 536741), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 12, 59, 14, 537744), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 12, 59, 14, 538748), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 12, 59, 14, 537744), null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Order_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message_type', models.CharField(blank=True, choices=[('chat', 'Chat Message'), ('activity', 'Activity Message')], default='', max_length=300, null=True)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.order_conversation')),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_message_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Message',
                'verbose_name_plural': 'Order Messages',
            },
        ),
        migrations.CreateModel(
            name='Order_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.CharField(blank=True, max_length=1000, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to=settings.AUTH_USER_MODEL)),
                ('delivered_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_to', to=settings.AUTH_USER_MODEL)),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
            ],
            options={
                'verbose_name': 'Order Delivery',
                'verbose_name_plural': 'Order Delivery',
            },
        ),
        migrations.CreateModel(
            name='Message_Response_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recieved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Response Analysis',
                'verbose_name_plural': 'Message Response Analysys',
            },
        ),
    ]
