# Generated by Django 4.0.8 on 2022-10-29 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0082_order_conversation_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_delivery',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('completed', 'Completed')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 14, 23, 17, 557766), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 14, 23, 17, 557766), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 14, 23, 17, 557766), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 29, 14, 23, 17, 557766), null=True),
        ),
    ]
