# Generated by Django 4.0.8 on 2022-10-30 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0084_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_conversation',
            name='conversation_type',
            field=models.CharField(blank=True, choices=[('activity', 'Activity'), ('message', 'Msessage')], default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order_conversation',
            name='resolution',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_con_resolution', to='kworkapp.user_order_resolution'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 38, 57, 113534), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 38, 57, 113534), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 38, 57, 113534), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 38, 57, 113534), null=True),
        ),
        migrations.AlterField(
            model_name='user_order_resolution',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('cancel', 'Cancel Order'), ('extention', 'Extension Days'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='', max_length=300, null=True),
        ),
    ]
