# Generated by Django 4.0.8 on 2022-10-30 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0085_order_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_conversation',
            name='conversation_type',
        ),
        migrations.RemoveField(
            model_name='order_conversation',
            name='resolution',
        ),
        migrations.AddField(
            model_name='order_message',
            name='resolution',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_con_resolution', to='kworkapp.user_order_resolution'),
        ),
        migrations.AddField(
            model_name='user_order_resolution',
            name='order_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 22, 10, 12, 599205), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 22, 10, 12, 599205), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 22, 10, 12, 599205), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 22, 10, 12, 599205), null=True),
        ),
        migrations.AlterField(
            model_name='order_delivery',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('completed', 'Completed'), ('draft', 'Draft')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_order_resolution',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='', max_length=300, null=True),
        ),
    ]
