# Generated by Django 4.0.8 on 2022-10-31 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0087_chatwords_alter_withdrawal_parameters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_post_request',
            name='service_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='buyer_post_request',
            name='service_images',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='buyer_reviews',
            name='review_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 13, 15, 59, 276761), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 13, 15, 59, 276761), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 13, 15, 59, 277762), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 13, 15, 59, 277762), null=True),
        ),
        migrations.AlterField(
            model_name='request_offers',
            name='extra_parameters',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='request_offers',
            name='offer_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='seller_reviews',
            name='review_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='topicdetails',
            name='topic_Desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
