# Generated by Django 4.0.8 on 2022-11-01 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0088_alter_buyer_post_request_service_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_order_resolution',
            name='resolution_personal_msg',
        ),
        migrations.AddField(
            model_name='user_order_resolution',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_order_resolution',
            name='raised_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 19, 14, 24, 414387), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 19, 14, 24, 414387), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 19, 14, 24, 416386), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 19, 14, 24, 415387), null=True),
        ),
    ]
