# Generated by Django 4.0.8 on 2022-11-04 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0092_user_order_resolution_ext_new_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdrawal_Parameters',
            new_name='Addon_Parameters',
        ),
        migrations.AlterModelOptions(
            name='addon_parameters',
            options={'verbose_name': 'Add On Parameter', 'verbose_name_plural': 'Add On Parameters'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 12, 27, 48, 737764), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 12, 27, 48, 737764), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 12, 27, 48, 738765), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 12, 27, 48, 738765), null=True),
        ),
    ]
