# Generated by Django 4.0.8 on 2022-11-04 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0096_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 1, 7, 16341), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 1, 7, 16341), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 1, 7, 17341), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 1, 7, 16341), null=True),
        ),
        migrations.CreateModel(
            name='Withdrawal_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('paypal', 'Paypal'), ('flutterwave', 'Flutterwave')], default='', max_length=300, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('payment_status', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('payment_currency', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('refund_amount', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('processing_fees', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('total_amount', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('paypal_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('paypal_email', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('flutter_account_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('flutter_app_fee', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('flutter_pay_type', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('gig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworkapp.usergigs')),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_paid_by', to=settings.AUTH_USER_MODEL)),
                ('paid_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_paid_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Transaction',
                'verbose_name_plural': 'Withdrawal Transactions',
            },
        ),
        migrations.CreateModel(
            name='User_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('refund_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('clearence_status', models.CharField(blank=True, choices=[('cleared', 'Cleared'), ('pending', 'Pending')], default='', max_length=300, null=True)),
                ('cleared_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
                ('r_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.withdrawal_transactions')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_order_resolution')),
            ],
            options={
                'verbose_name': 'Order Refund',
                'verbose_name_plural': 'Order Refunds',
            },
        ),
        migrations.CreateModel(
            name='User_Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_amount', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('earning_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('clearence_status', models.CharField(blank=True, choices=[('cleared', 'Cleared'), ('pending', 'Pending')], default='', max_length=300, null=True)),
                ('cleared_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
                ('r_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.withdrawal_transactions')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_order_resolution')),
            ],
            options={
                'verbose_name': 'Order Earning',
                'verbose_name_plural': 'Order Earnings',
            },
        ),
    ]
