# Generated by Django 4.0.8 on 2022-11-04 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0098_user_earnings_clearence_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_earnings',
            name='aval_with',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_refund',
            name='aval_with',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 8, 9, 89087), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 8, 9, 89087), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 8, 9, 89087), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 4, 20, 8, 9, 89087), null=True),
        ),
        migrations.AlterField(
            model_name='user_earnings',
            name='clearence_status',
            field=models.CharField(blank=True, choices=[('cleared', 'Cleared'), ('pending', 'Pending'), ('initiated', 'Initiated')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_earnings',
            name='earning_amount',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_refund',
            name='clearence_status',
            field=models.CharField(blank=True, choices=[('cleared', 'Cleared'), ('pending', 'Pending'), ('initiated', 'Initiated')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user_refund',
            name='refund_amount',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
