# Generated by Django 4.0.8 on 2022-11-05 11:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0100_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('paypal', 'Paypal'), ('flutterwave', 'Flutterwave')], default='', max_length=300, null=True, unique=True)),
                ('secrete_key', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('private_key', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Api Key',
                'verbose_name_plural': 'Api Keys',
            },
        ),
        migrations.RemoveField(
            model_name='user_earnings',
            name='r_transaction',
        ),
        migrations.RemoveField(
            model_name='user_refund',
            name='r_transaction',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 11, 39, 47, 583073), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 11, 39, 47, 583073), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 11, 39, 47, 584074), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 5, 11, 39, 47, 584074), null=True),
        ),
        migrations.DeleteModel(
            name='Withdrawal_Transactions',
        ),
    ]
