# Generated by Django 4.0.8 on 2022-11-07 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0112_rename_buyer_response_seller_reviews_seller_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 12, 50, 372113), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 12, 50, 372113), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 12, 50, 373114), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 12, 50, 372113), null=True),
        ),
        migrations.AlterField(
            model_name='spamdetection',
            name='detected_word',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
