# Generated by Django 4.0.8 on 2022-11-07 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0114_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spamdetection',
            options={'verbose_name': 'Spam Detection', 'verbose_name_plural': 'SDetectionspam '},
        ),
        migrations.AddField(
            model_name='spamdetection',
            name='sent_status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('pending', 'Pending')], default='pending', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 39, 3, 23842), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 39, 3, 23842), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 39, 3, 23842), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 12, 39, 3, 23842), null=True),
        ),
    ]
