# Generated by Django 4.0.8 on 2022-11-07 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0115_alter_spamdetection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spamdetection',
            options={'verbose_name': 'Spam Detection', 'verbose_name_plural': 'Spam Detections '},
        ),
        migrations.AddField(
            model_name='user_earnings',
            name='affiliate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_earnings',
            name='earning_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('affiliate', 'Affiliate')], default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_earnings',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earning_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 18, 1, 25, 236543), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 18, 1, 25, 236543), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 18, 1, 25, 236543), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 18, 1, 25, 236543), null=True),
        ),
        migrations.AlterField(
            model_name='referral_users',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reff_affiliate_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
