# Generated by Django 4.0.8 on 2022-11-07 23:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0118_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 23, 0, 11, 89972), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 23, 0, 11, 89972), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 23, 0, 11, 90978), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 7, 23, 0, 11, 90978), null=True),
        ),
        migrations.AlterField(
            model_name='seller_reviews',
            name='buyer_resp_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user_earnings',
            name='earning_type',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('affiliate', 'Affiliate'), ('tip', 'Tip')], default='', max_length=300, null=True),
        ),
    ]
