# Generated by Django 4.0.8 on 2022-11-08 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0120_user_refund_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_refund',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='cancelled', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 8, 18, 1, 3, 273628), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 8, 18, 1, 3, 273628), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 8, 18, 1, 3, 274630), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 8, 18, 1, 3, 273628), null=True),
        ),
    ]
