# Generated by Django 4.0.8 on 2022-11-09 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0134_user_transactions_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 11, 57, 7, 282143), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 11, 57, 7, 282143), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 11, 57, 7, 283144), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 11, 57, 7, 282143), null=True),
        ),
        migrations.AlterField(
            model_name='user_transactions',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('rufunded', 'Rufunded')], default='', max_length=300, null=True),
        ),
    ]
