# Generated by Django 4.0.8 on 2022-11-09 13:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0135_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits_used_amount',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn_amount',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_earnings',
            name='withdrawn_amount',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_earnings',
            name='withdrawn_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_refund',
            name='credit_used',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 13, 53, 35, 609494), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 13, 53, 35, 609494), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 13, 53, 35, 610494), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 13, 53, 35, 609494), null=True),
        ),
    ]
