# Generated by Django 4.0.8 on 2022-11-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0142_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order_activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('delivered', 'Delivered'), ('cancel', 'Cancelled'), ('completed', 'Completed'), ('withdrawal', 'Withdrawal'), ('credit', 'Credit')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 18, 56, 38, 579677), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 18, 56, 38, 579677), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 18, 56, 38, 579677), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 18, 56, 38, 579677), null=True),
        ),
    ]
