# Generated by Django 4.0.8 on 2022-11-09 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0143_user_order_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 19, 6, 40, 450976), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 19, 6, 40, 450976), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 19, 6, 40, 451976), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 19, 6, 40, 450976), null=True),
        ),
        migrations.AlterField(
            model_name='user_order_activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('delivered', 'Delivered'), ('cancel', 'Cancelled'), ('extension', 'Extension'), ('completed', 'Completed'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('credit', 'Credit')], default='', max_length=300, null=True),
        ),
    ]
