# Generated by Django 4.0.8 on 2022-11-11 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0145_remove_buyer_reviews_seller_resp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_transactions',
            name='credits_used',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_transactions',
            name='paid_for',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('tip', 'Tip')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 17, 52, 34, 321030), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 17, 52, 34, 321030), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 17, 52, 34, 321030), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 11, 17, 52, 34, 321030), null=True),
        ),
    ]
