# Generated by Django 4.0.8 on 2022-11-12 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0146_user_transactions_credits_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_earnings',
            name='withdrawn_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 20, 38, 33, 45340), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 20, 38, 33, 45340), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 20, 38, 33, 46341), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 20, 38, 33, 46341), null=True),
        ),
    ]
