# Generated by Django 4.0.8 on 2022-11-13 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0149_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_users',
            name='buyer_affi_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral_users',
            name='seller_affi_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 32, 8, 776183), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 32, 8, 776183), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 32, 8, 777184), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 32, 8, 777184), null=True),
        ),
        migrations.AlterField(
            model_name='user_order_activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('delivered', 'Delivered'), ('cancel', 'Cancelled'), ('e_cancel', 'E_Cancelled'), ('extension', 'Extension'), ('completed', 'Completed'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('credit', 'Credit'), ('pending', 'Pending'), ('tip', 'tip'), ('affiliate', 'Affiliate')], default='', max_length=300, null=True),
        ),
    ]
