# Generated by Django 4.0.8 on 2022-11-13 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0151_user_order_activity_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_order_activity',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_order_activity',
            name='activity_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_order_activity',
            name='activity_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 48, 22, 527225), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 48, 22, 527225), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 48, 22, 527225), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 12, 48, 22, 527225), null=True),
        ),
    ]
