# Generated by Django 4.0.8 on 2022-11-13 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0160_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 21, 25, 55, 330501), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 21, 25, 55, 330501), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 21, 25, 55, 330501), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 21, 25, 55, 330501), null=True),
        ),
        migrations.CreateModel(
            name='Withdrwal_initiated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_amount', models.CharField(blank=True, max_length=500, null=True)),
                ('withdrawal_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('iniated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('withdrawan_status', models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('partial', 'Partial'), ('sucess', 'Sucess')], default='', max_length=300, null=True)),
                ('withdrawn_date', models.DateTimeField(blank=True, default='', null=True)),
                ('order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kworkapp.user_orders')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawals',
                'verbose_name_plural': 'Withdrawals',
            },
        ),
    ]
