# Generated by Django 4.0.8 on 2022-11-14 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0161_notification_commands_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon_parameters',
            name='no_of_days',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 12, 37, 24, 606198), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 12, 37, 24, 606198), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 12, 37, 24, 608198), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 12, 37, 24, 607198), null=True),
        ),
        migrations.AlterField(
            model_name='user_order_activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('delivered', 'Delivered'), ('cancel', 'Cancelled'), ('e_cancel', 'E_Cancelled'), ('extension', 'Extension'), ('completed', 'Completed'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('credit', 'Credit'), ('pending', 'Pending'), ('cleared', 'Cleared'), ('tip', 'tip'), ('affiliate', 'Affiliate')], default='', max_length=300, null=True),
        ),
    ]
