# Generated by Django 4.0.8 on 2022-11-14 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0162_alter_addon_parameters_no_of_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrwal_initiated',
            name='order_no',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 14, 43, 32, 656517), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 14, 43, 32, 656517), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 14, 43, 32, 656517), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 14, 43, 32, 656517), null=True),
        ),
        migrations.AlterField(
            model_name='withdrwal_initiated',
            name='withdrawan_status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('sucess', 'Sucess')], default='', max_length=300, null=True),
        ),
    ]
