# Generated by Django 4.0.8 on 2022-11-14 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0165_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrwal_initiated',
            old_name='iniated_date',
            new_name='initiated_date',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 15, 38, 46, 607118), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 15, 38, 46, 607118), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 15, 38, 46, 607118), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 14, 15, 38, 46, 607118), null=True),
        ),
    ]
