# Generated by Django 4.0.8 on 2022-11-15 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0170_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='convers_type',
            field=models.CharField(blank=True, choices=[('block', 'Blocked'), ('delete', 'Delete'), ('active', 'Active')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 15, 11, 27, 29, 160946), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 15, 11, 27, 29, 160946), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 15, 11, 27, 29, 160946), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 15, 11, 27, 29, 160946), null=True),
        ),
    ]
