# Generated by Django 4.0.8 on 2022-11-17 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0175_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_post_request',
            name='individual_request_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('decline', 'Decline'), ('withdrawn', 'Withdrawn')], default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 11, 12, 39890), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 11, 12, 39890), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 11, 12, 39890), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 11, 12, 39890), null=True),
        ),
    ]
