# Generated by Django 4.0.8 on 2022-11-18 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0183_message_request_offers_id_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification_commands',
            options={'verbose_name': 'Notification Setting', 'verbose_name_plural': 'Notification Settings'},
        ),
        migrations.AddField(
            model_name='order_delivery',
            name='current_revision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order_delivery',
            name='total_revision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 18, 18, 2, 11, 846036), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 18, 18, 2, 11, 846036), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 18, 18, 2, 11, 847037), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 18, 18, 2, 11, 847037), null=True),
        ),
    ]
