# Generated by Django 4.0.8 on 2022-11-19 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0189_rename_customnotifications_kworkcustomnotifications_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KworkCustomNotifications',
            new_name='CustomNotifications',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 23, 7, 6, 848791), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 23, 7, 6, 848791), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 23, 7, 6, 848791), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 23, 7, 6, 848791), null=True),
        ),
    ]
