# Generated by Django 4.0.8 on 2022-11-21 10:09

import datetime
from django.db import migrations, models
import kworkapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0192_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Max width and height of the image will be 460:100', null=True, upload_to=kworkapp.models.logofilename)),
                ('slug', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.AlterModelOptions(
            name='message_response_time',
            options={'verbose_name': 'Message Interval', 'verbose_name_plural': 'Message Interval'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 10, 9, 43, 184915), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 10, 9, 43, 184915), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 10, 9, 43, 186916), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 21, 10, 9, 43, 185916), null=True),
        ),
    ]
