# Generated by Django 4.0.8 on 2022-11-27 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0193_logoimages_alter_message_response_time_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_keys',
            name='mail_address',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='api_keys',
            name='mail_host',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='api_keys',
            name='mail_password',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='api_keys',
            name='mail_port',
            field=models.CharField(blank=True, choices=[('587', '587'), ('25', '25'), ('465', '465')], default='587', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notification_commands',
            name='mail_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_rating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 43, 1, 811827), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 43, 1, 811827), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 43, 1, 828686), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 43, 1, 827684), null=True),
        ),
    ]
