# Generated by Django 4.0.8 on 2022-11-27 11:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0194_api_keys_mail_address_api_keys_mail_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTP_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_host', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('mail_address', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('mail_password', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('mail_port', models.CharField(blank=True, choices=[('587', '587'), ('25', '25'), ('465', '465')], default='587', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.RemoveField(
            model_name='api_keys',
            name='mail_address',
        ),
        migrations.RemoveField(
            model_name='api_keys',
            name='mail_host',
        ),
        migrations.RemoveField(
            model_name='api_keys',
            name='mail_password',
        ),
        migrations.RemoveField(
            model_name='api_keys',
            name='mail_port',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 53, 25, 15392), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 53, 25, 15392), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 53, 25, 15392), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 27, 11, 53, 25, 15392), null=True),
        ),
    ]
