# Generated by Django 4.0.8 on 2022-12-05 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0200_order_message_is_read_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_message',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 20, 30, 27, 431484), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 20, 30, 27, 431484), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 20, 30, 27, 432485), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 20, 30, 27, 432485), null=True),
        ),
    ]
