# Generated by Django 4.0.8 on 2022-12-08 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0201_message_mail_sent_order_message_mail_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 20, 56, 12, 433815), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 20, 56, 12, 433815), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 20, 56, 12, 434817), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 8, 20, 56, 12, 434817), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_delivery',
            field=models.CharField(blank=True, default='0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_earnings',
            name='credit_used',
            field=models.CharField(blank=True, default='0.0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_refund',
            name='credit_used',
            field=models.CharField(blank=True, default='0.0', max_length=500, null=True),
        ),
    ]
