# Generated by Django 4.0.8 on 2022-12-10 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import kworkapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0209_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLevels4',
            fields=[
                ('level_name', models.CharField(blank=True, default='', help_text='Actual Seller Level Name Which will displayed in front.', max_length=500, null=True)),
                ('level_slug', models.CharField(default='', help_text='slug name should follow the sequence of levels, i.e, level1, level2, etc.', max_length=500, primary_key=True, serialize=False)),
                ('No_of_gigs', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('No_of_offers', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('level_badge', models.FileField(blank=True, max_length=255, null=True, upload_to=kworkapp.models.badgeupload)),
                ('up_order_amount', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('up_order_count', models.CharField(blank=True, default='0', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Seller Level',
                'verbose_name_plural': 'Seller Levels',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 20, 20, 969353), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 20, 20, 969353), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 20, 20, 969353), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 20, 20, 969353), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_delivery',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_level',
            field=models.CharField(blank=True, default='level1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_level', to='kworkapp.sellerlevels4'),
        ),
    ]
