# Generated by Django 4.0.8 on 2022-12-10 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0210_sellerlevels4_delete_sellerlevels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_last_delivery',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 23, 29, 533746), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 23, 29, 533746), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 23, 29, 533746), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 18, 23, 29, 533746), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_delivery',
            field=models.CharField(blank=True, default='1', max_length=500, null=True),
        ),
    ]
