# Generated by Django 4.0.8 on 2022-12-10 20:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0211_delete_sellerlevels_user_user_last_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerLevels',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 20, 53, 18, 266761), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 20, 53, 18, 266761), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 20, 53, 18, 267762), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 20, 53, 18, 266761), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_last_delivery',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
