# Generated by Django 4.0.8 on 2022-12-10 21:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0213_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_last_delivery',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 21, 3, 17, 74524), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 21, 3, 17, 74524), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 21, 3, 17, 74524), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 21, 3, 17, 74524), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_last_delivery',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
