# Generated by Django 4.0.8 on 2022-12-10 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0214_user_u_last_delivery_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 22, 3, 48, 114479), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 22, 3, 48, 114479), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 22, 3, 48, 114479), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 10, 22, 3, 48, 114479), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(blank=True, default='level1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_level', to='kworkapp.sellerlevels4'),
        ),
    ]
