# Generated by Django 4.0.8 on 2022-12-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0215_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 12, 41, 5, 462642), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 12, 41, 5, 462642), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 12, 41, 5, 462642), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 11, 12, 41, 5, 462642), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('warning', 'WARNING'), ('blocked', 'BLOCKED')], default='active', max_length=200, null=True),
        ),
    ]
