# Generated by Django 4.0.8 on 2022-12-12 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0217_sellerlevels4_record_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unblocked_count',
            field=models.CharField(blank=True, default='0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 12, 23, 8, 3, 216917), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 12, 23, 8, 3, 216917), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 12, 23, 8, 3, 216917), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 12, 23, 8, 3, 216917), null=True),
        ),
    ]
