# Generated by Django 4.0.8 on 2022-12-13 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0218_user_unblocked_count_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 12, 31, 33, 302105), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 12, 31, 33, 302105), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 12, 31, 33, 303105), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 13, 12, 31, 33, 302105), null=True),
        ),
        migrations.AlterField(
            model_name='user_transactions',
            name='transaction_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('rufunded', 'Rufunded')], default='', max_length=300, null=True),
        ),
    ]
