# Generated by Django 4.0.8 on 2022-12-17 21:27

import datetime
import django.core.validators
from django.db import migrations, models
import kworkapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0221_alter_buyer_post_request_service_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtopicdetails',
            name='upload_pdf',
            field=models.FileField(blank=True, help_text='Only pdf files are allowed.', max_length=255, null=True, upload_to=kworkapp.models.servicefilename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.FileField(blank=True, help_text='Max width and height of the image will be 480:330', max_length=255, null=True, upload_to=kworkapp.models.categoryfilename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 21, 26, 58, 87077), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 21, 26, 58, 87077), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 21, 26, 58, 88077), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='image',
            field=models.FileField(blank=True, help_text='Only jpg, png, jpeg images are allowed.', max_length=255, null=True, upload_to=kworkapp.models.servicefilename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 21, 26, 58, 87077), null=True),
        ),
        migrations.AlterField(
            model_name='logoimages',
            name='image',
            field=models.FileField(blank=True, help_text='Max width and height of the image will be 460:100', null=True, upload_to=kworkapp.models.logofilename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='sellerlevels4',
            name='level_badge',
            field=models.FileField(blank=True, help_text='Only jpg, png, jpeg images are allowed.', max_length=255, null=True, upload_to=kworkapp.models.badgeupload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='image',
            field=models.FileField(blank=True, help_text='Max width and height of the image will be 480:330', max_length=255, null=True, upload_to=kworkapp.models.subcategoryfilename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
