# Generated by Django 4.0.8 on 2022-12-18 18:10

import datetime
import django.core.validators
from django.db import migrations, models
import kworkapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0222_learningtopicdetails_upload_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_orders',
            name='incoming_request',
            field=models.CharField(blank=True, choices=[('site', 'Site'), ('admin', 'Admin')], default='admin', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 18, 18, 10, 5, 217899), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 18, 18, 10, 5, 217899), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 18, 18, 10, 5, 217899), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='upload_pdf',
            field=models.FileField(blank=True, default=None, help_text='Only pdf files are allowed.', max_length=255, null=True, upload_to=kworkapp.models.servicefilename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='video_url',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 18, 18, 10, 5, 217899), null=True),
        ),
    ]
