# Generated by Django 4.0.8 on 2022-12-23 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworkapp', '0236_adminlogging_buyer_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogging',
            name='buyer_request',
        ),
        migrations.RemoveField(
            model_name='adminlogging',
            name='contact_us',
        ),
        migrations.RemoveField(
            model_name='adminlogging',
            name='gig_Details',
        ),
        migrations.RemoveField(
            model_name='adminlogging',
            name='withdrawal',
        ),
        migrations.AddField(
            model_name='adminlogging',
            name='reqst_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adminlogging',
            name='reqst_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 23, 12, 59, 20, 177969), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 23, 12, 59, 20, 177969), null=True),
        ),
        migrations.AlterField(
            model_name='learningtopicdetails',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 23, 12, 59, 20, 177969), null=True),
        ),
        migrations.AlterField(
            model_name='learntopics',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 23, 12, 59, 20, 177969), null=True),
        ),
    ]
